const badgeDefinitions = [
  {
    badgeType: 'first_blood',
    name: 'First Blood',
    description: 'Selesaikan level pertamamu dengan sukses!',
    icon: 'Swords',
    rarity: 'common',
    points: 10,
    target: 1,
  },
  {
    badgeType: 'speedster',
    name: 'Speedster',
    description: 'Selesaikan satu level di bawah 5 menit.',
    icon: 'Zap',
    rarity: 'uncommon',
    points: 20,
    target: 1,
  },
  {
    badgeType: 'perfectionist',
    name: 'Perfectionist',
    description: 'Raih skor 100% pada 5 level berbeda.',
    icon: 'Target',
    rarity: 'epic',
    points: 100,
    target: 5,
  },
  {
    badgeType: 'marathon',
    name: 'Marathon',
    description: 'Selesaikan total 10 level pembelajaran.',
    icon: 'Footprints',
    rarity: 'rare',
    points: 50,
    target: 10,
  },
  {
    badgeType: 'champion',
    name: 'Top 10 Champion',
    description: 'Tembus peringkat 10 besar di Leaderboard.',
    icon: 'Trophy',
    rarity: 'epic',
    points: 100,
    target: 1,
  },
  {
    badgeType: 'legend',
    name: 'The Legend',
    description: 'Selesaikan semua level yang tersedia di SAKA!',
    icon: 'Crown',
    rarity: 'legendary',
    points: 500,
    target: 1,
  },
  {
    badgeType: 'streak_7',
    name: '7-Day Warrior',
    description: 'Pertahankan Daily Streak selama 7 hari berturut-turut.',
    icon: 'Flame',
    rarity: 'uncommon',
    points: 30,
    target: 7,
  },
  {
    badgeType: 'streak_30',
    name: 'Monthly Master',
    description: 'Pertahankan Daily Streak selama 30 hari berturut-turut!',
    icon: 'CalendarDays',
    rarity: 'legendary',
    points: 300,
    target: 30,
  },
  {
    badgeType: 'teacher',
    name: 'Helpful Teacher',
    description: 'Bantu 5 siswa lain (Fitur Komunitas Mendatang).',
    icon: 'Users',
    rarity: 'rare',
    points: 50,
    target: 5,
  },
  {
    badgeType: 'consistent',
    name: 'Mr. Consistent',
    description: 'Login setiap hari selama sebulan penuh.',
    icon: 'CheckCircle',
    rarity: 'epic',
    points: 150,
    target: 30,
  },
  {
    badgeType: 'night_owl',
    name: 'Night Owl',
    description: 'Selesaikan level antara jam 10 malam dan 4 pagi.',
    icon: 'Moon',
    rarity: 'uncommon',
    points: 20,
    target: 1,
  },
  {
    badgeType: 'early_bird',
    name: 'Early Bird',
    description: 'Selesaikan level antara jam 4 pagi dan 8 pagi.',
    icon: 'Sun',
    rarity: 'uncommon',
    points: 20,
    target: 1,
  },
  {
    badgeType: 'sharpshooter',
    name: 'Sharpshooter',
    description: 'Jawab 50 pertanyaan tanpa salah sama sekali.',
    icon: 'Crosshair',
    rarity: 'epic',
    points: 150,
    target: 50,
  },
  {
    badgeType: 'unstoppable',
    name: 'Unstoppable',
    description: 'Selesaikan 3 level dalam satu hari.',
    icon: 'Rocket',
    rarity: 'rare',
    points: 50,
    target: 3,
  },
  {
    badgeType: 'scholar',
    name: 'Scholar',
    description: 'Selesaikan semua tutorial onboarding.',
    icon: 'GraduationCap',
    rarity: 'common',
    points: 10,
    target: 1,
  },
  {
    badgeType: 'weekend_warrior',
    name: 'Weekend Warrior',
    description: 'Selesaikan 5 level selama akhir pekan (Sabtu-Minggu).',
    icon: 'Tent',
    rarity: 'rare',
    points: 60,
    target: 5,
  },
  {
    badgeType: 'flawless_week',
    name: 'Flawless Week',
    description: 'Raih skor 100% akurasi selama 7 hari berturut-turut.',
    icon: 'Sparkles',
    rarity: 'legendary',
    points: 400,
    target: 7,
  },
  {
    badgeType: 'polyglot',
    name: 'Polyglot',
    description: 'Kuasai kosakata dari 5 topik yang berbeda.',
    icon: 'Globe',
    rarity: 'epic',
    points: 200,
    target: 5,
  },
  {
    badgeType: 'treasure_hunter',
    name: 'Treasure Hunter',
    description: 'Temukan easter egg rahasia pertamamu.',
    icon: 'Map',
    rarity: 'rare',
    points: 75,
    target: 1,
  },
  {
    badgeType: 'point_hoarder',
    name: 'Point Hoarder',
    description: 'Kumpulkan total 5.000 poin pembelajaran.',
    icon: 'Coins',
    rarity: 'legendary',
    points: 500,
    target: 5000,
  },
  {
    badgeType: 'revival',
    name: 'Revival',
    description: 'Pulihkan streak yang hampir hilang menggunakan Streak Freeze.',
    icon: 'HeartPulse',
    rarity: 'rare',
    points: 50,
    target: 1,
  }
];

module.exports = badgeDefinitions;
